# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8468d7d669080b81569bb25f1a1a5b8d45ff4f6d746fad41839d79b98775b8055a0ac80aac51108ea9a1bd812f9e20c3673475563f4654c5029dd10147c51eb1

test:
  secret_key_base: 16bb1303003737e0256022ca9f81adaf32be64d2d388d2f30a84a30a7fe3666712af08bdf30719d72eba68203501cddb0ce99036cebe7864ddb03d5b62265b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
